### ISSUE TITLE
bin/import_subjects broken - no subjects imported

### ISSUE THREAD

**Issue by drtjmb** [eprints/eprints#291]
````
 63 
 64         # percent-decode "%3A" to ":"
 65         @vals = map { s/%3A/:/g } @vals;
 66 
````

Will effectively erase the content of @vals so no subject data is imported.

@phluid61 - don't modify $_ in a map, and remember that the output of s/// is the success code not the altered string.

Try:

````
@vals = map { s/%3A/:/g; $_ } @vals; # still modifies $_
````

or better

````
@vals = map { ( my $s = $_ ) =~ s/%3A/:/g; $s } @vals;
````

**Comment by phluid61** [comment]
Sorry, my mistake was in assigning it back to `@vals`. What I meant to write was:

    map { s/%3A/:/g } @vals

Is there a reason not to modify `$_`?

**Comment by drtjmb** [comment]
@phluid61 - I think it's one of those rules of thumb handed down by the perl monks - my guess is there is no harm in modifying $_ in this case but not a habit you generally want to get into :-) Thanks for making the change.

**Comment by UmbrellaDish** [comment]
In Perl Best Practices, Damian Conway recommends for loop in this case of in-place modification, reserving map for really trivial read, process and stuff results elsewhere:

    for ( @values ) { s/%3A/:/g }

When the loop grows, there is an option to write `for my $varname (...) {...}`, then you've got a named *alias* instead of `$_`.
