### ISSUE TITLE
subjects and divisions shown in both languages after upgrade to 3.3.13

### ISSUE THREAD

**Issue by dpavlin** [eprints/eprints#295]
After upgrade to eprints 3.3.13 debian package, our subject and department views started showing both languages for each value separated by comma as you can see here:

http://darhiv.ffzg.unizg.hr/view/subjects/

and here:

http://darhiv.ffzg.unizg.hr/view/divisions/

**Comment by gutknecht** [comment]
I'm able to confirm that. In my case there even are three languages:
![subjects_too many languages](https://cloud.githubusercontent.com/assets/3227412/6239234/1dc85278-b702-11e4-957e-04c746ded317.png)

**Comment by zecg** [comment]
Affected as well: 
https://repozitorij.fsb.hr/view/subjects/
https://repozitorij.fsb.hr/view/divisions/

**Comment by Izoniz** [comment]
The same problem.
http://eprints.oa.edu.ua/view/subjects/
http://eprints.oa.edu.ua/view/divisions/

**Comment by alenkovich** [comment]
Same here:
http://eprints.grf.unizg.hr/view/subjects/

**Comment by drtjmb** [comment]
Please try applying the changes in the pull request and then updating your subjects/divisions menus eg. bin/generate_views foo --view subjects --generate menus

**Comment by alenkovich** [comment]
Hi!

Thanks Tim, .. we were also looking into those changes but simple 
"Regenerate Views" in admin web interface didn't trigger the change, is 
this possible?

Anyway, I can confirm it's working now :)

**Comment by dpavlin** [comment]
Thanks, #306 fixes this issue, so I will close this one to avoid duplication.

**Comment by drtjmb** [comment]
Hi Alen,

“Regenerate views” just sets the cache as dirty so that view pages are regenerated on next request. This doesn’t make Apache/mod_perl reload the EPrints modules though, so an apache restart would be required as well.

Regards,

Tim

Timothy Miles-Board
Web & Repositories Development Specialist, University of London Computer Centre
020 7863 1342  |  07742 970 351  | timothy.miles-board@london.ac.uk<mailto:timothy.miles-board@london.ac.uk>
The University of London is an exempt charity in England and Wales
