### ISSUE TITLE
Subjects and Divisions lost on upgrade

### ISSUE THREAD

**Issue by Martynhsmith** [eprints/eprints#297]
We upgraded from 3.3.12-1.el6 to 3.3.13-1.el6 from the rpm.eprints.org repository
and we lost the 'root subjects/divisions' then after a reboot we lost everything

We downgraded again and restored the tables and to prove a point, upgraded and it goes wrong again. (It feels like the database structure has changed with extra fields, as it displays undefined)

we had the original Library of Congress Subject Areas but a change divisional structure.

We are now back at  3.3.12-1.el6 and have stopped automatic update - which I guess will cause a problem soon!

Martyn

**Comment by alenkovich** [comment]
Hi!
We had the same problem but the solution is very simple.. it's not a bug.

After upgrade through debian package our sysadmin did only "epadmin upgrade" .. but one should also run "epadmin update" because there are some changes in default fields configuration.

I'm not sure if this was intended as an postinstall taks but it solved our problem.

So, in brief:
 $ ./bin/epadmin update <repo_id>
 Added roles to dataset user
 Added expiry_date to dataset request
 Added code to dataset request
 Added name to dataset subject
 Added sortvalue to dataset subject
 0 datasets added
 5 fields added
 0 counters were added

 $ ./bin/epadmin update <repo_id>

**Comment by jiadiyao** [comment]
Hi Martyn, 

We have added some extra fields to the subject dataset to provide extra functionality. 

It is essential that you run 

$ ./bin/epadmin upgrade
followed by 
$ ./bin/epadmin update

after you upgraded your EPrints from an older version.

**Comment by MrkGrgsn** [comment]
Why not include the update step in the upgrade for this version since you know there are new fields?
