### ISSUE TITLE
Display DOIs according to the CrossRef guidelines

### ISSUE THREAD

**Issue by zuphilip** [eprints/eprints#421]
Crossref has just announce to change the guidelines to display dois: http://blog.crossref.org/2016/09/new-crossref-doi-display-guidelines.html . This includes the following suggestions
 1. Show the doi as an url and with any prefix `DOI: ` or pseudo-protocol `doi:`. Actually this is already part of the [2011 guidelines](http://www.crossref.org/02publishers/doi_display_guidelines.html) and there the background is also explained: "Previously, Crossref recommended that DOIs be displayed in the format doi:10.NNNN/doisuffix At the time that the DOI system was first envisioned, it was thought that doi: would become native to browsers and automatically resolve DOIs. It appears unlikely that that will happen."
 2. Drop the `dx` in the url. I guess this is already achieved with the commit https://github.com/eprints/eprints/commit/dcbaa0f3ff607acf70a7be9d336e382e4dc003cf by @jesusbagpuss 
 3. Prefer `https` over `http` as @afandian also explained in the csl-styles discussion.

Thus, the best practice according to the CrossRef, which is a common view with DataCite, is

> **So–it’s simple–always make the DOI a full link – [https://doi.org/10.1006/jmbi.1995.0238](https://doi.org/10.1006/jmbi.1995.0238) – even when it’s on the abstract or full text page of the content that the DOI identifies – and use “https://doi.org/”.**

**Comment by afandian** [comment]
Thanks for getting this started!

**Comment by icklecows** [comment]
I think this is something that should be done, although it's notable that EPrints uses the id_number field rather than a dedicated DOI field to record these.  The script that renders the DOI is:

https://github.com/eprints/eprints/blob/3.3/perl_lib/EPrints/Extras.pm#L301

This is already just using doi.org, so it's only updating to https that's required I think.

**Comment by afandian** [comment]
Yes, looking at that code (which looks good FWIW), it should be a single character fix!

**Comment by icklecows** [comment]
Not quite - the regexp that picks up whether or not it is a DOI also needs to recognise DOIs input using the current guidelines.  But it's nothing more than that.

**Comment by afandian** [comment]
Yes, I missed that.

**Comment by zuphilip** [comment]
Moreover, we should render the doi as a link (see point 1). I guess with something like
```diff
	my $url = "http://doi.org/$value";
	my $link = $session->render_link( $url, "_blank" ); 
-	$link->appendChild( $session->make_text( $value ) );
+	$link->appendChild( $session->make_text( $url) );
```

**Comment by icklecows** [comment]
Yes, good point.

**Comment by icklecows** [comment]
Do you want to do the pull request @zuphilip or shall I?

**Comment by zuphilip** [comment]
It would be great, when you can do these changes. (I am watching and learning then:-)

**Comment by mpbraendle** [comment]
Should not all plugins that handle DOI be adapted accordingly, e.g. the perl_lib/EPrints/Plugin/Import/DOI.pm plugin ?

It is not only about rendering, but if the CrossRef guideline explained in http://blog.crossref.org/2016/09/new-crossref-doi-display-guidelines.html begins to take effect, people will copy the full DOI URL into the form (which is intended by the guideline).
Are there other plugins we should be aware of? E.g. DOI field entry in the manage deposits and review workflow?

**Comment by afandian** [comment]
Agreed @mpbraendle, everywhere a DOI is expected a DOI should work, and DOIs are URLs (as per [guidelines going back at least 5 years](http://web.archive.org/web/20110815041329/http://www.crossref.org/02publishers/doi_display_guidelines.html), that's the earliest archived version I could find).

**Comment by icklecows** [comment]
OK, there are 15 files in eprints that match a search for "doi"

**No changes needed:**

- perl_lib/EPrints/Extras.pm - has already been updated
- lib/defaultcfg/cfg.d/plugins.pl
- perl_lib/EPrints/Plugin/Screen/Import/DOI.pm
- lib/defaultcfg/cfg.d/eprint_fields.pl
- perl_lib/URI/OpenURL.pm
- perl_lib/EPrints/Plugin/Export/RIS.pm
- perl_lib/SOAP/ISIWoK.pm

**Changes needed:**

- perl_lib/EPrints/Plugin/Import/DOI.pm - needs s adding to official url, but also does it need to do the same format check as the render script?
- lib/lang/en/phrases/system.xml - Phrase for importing DOI recommends the old format doi: rather than current.  Should be updated if the import script is made more flexible to accept URL formatted DOIs.
- tools/pirus_pingbackd - needs s? added to regexp

**Changes would improve these:**
- perl_lib/EPrints/Plugin/Export/DC.pm - not currently doing anything to the DOI field - should perhaps have a render script to standardise them as per Extras.pm?
- lib/cfg.d/rdf_triples_bibo.pl - probably needs updating as only seems to be checking for doi:
- perl_lib/EPrints/Plugin/Import/ISIWoK.pm - no change needed, although maybe it should look for the DOI field rather than assuming ID number?
- perl_lib/EPrints/Plugin/Import/ISIWoKXML.pm - no change needed, although maybe it should look for the DOI field rather than assuming ID number?

**Unknown:**
- perl_lib/ParaTools/CiteParser/Standard.pm - I have no idea what this is let alone what it's doing with DOIs, sorry

**Comment by denics** [comment]
should we create a function accepting the input listed by @afandian and rendering correctly ```https://doi.org/10.5555/12345678``` perhaps extending URI:: so that using it would be as easy as 
```
$mydoi = URI::doi->new("10.5555/12345678");
$mydoi = URI::doi->new("doi:10.5555/12345678");
```

**Comment by icklecows** [comment]
I think if there's uncertainty around whether we're keeping URI or using a dependency, it's probably best to fix the code as it is right now, and worry about DRYing it out later.

**Comment by phluid61** [comment]
It's worth pointing out that we consistently gloss the fact that URIs and DOIs have different character repertoires \[[link](http://www.doi.org/factsheets/DOIProxy.html#encoding)]. I'm +1 for patching the problems now, and designing a good DRY solution for the future.
