### ISSUE TITLE
Contents on EPrints repository is not featuring on Google Scholar

### ISSUE THREAD

**Issue by jiadiyao** [eprints/eprints#450]
**The problem**

A number of repository administrators have noticed that their content is not featuring in Google Scholar search results.
We have been in discussion with Google Scholar in regard to how it discovers and indexes the contents of EPrints repositories.

While EPrints is by design crafted to present its content to Google in best way, Google Scholar is encountering issues around the initial discovery of the content.
Google’s crawler processes 100s of billions of links, and it needs a clearer way to identify that a link is to an EPrints repository rather than a normal website. 
This would then allow Google Scholar to prioritise the crawling and indexing. Google Scholar already has EPrints specific rules in its crawler, and they are happy to update them.

**Comment by jiadiyao** [comment]
**The solution**

Google Scholar and I have come up with a plan to increase the discoverability of EPrints content.

Currently, records on EPrints have URLs which look like
http://YOUR-REPO/EPRINTID/ eg http://irep.ntu.ac.uk/12853/
However this is not easily identified as EPrints content without visiting the actual page, and Google has a lot of pages to visit.

We intend to promote the existing EPrints “URI” form of the links, which are easily identified as being EPrints content.
http://YOUR-REPO/id/eprint/EPRINTID/ eg http://irep.ntu.ac.uk/id/eprint/12853/
Currently the longer form of the URL redirects to the shorter version. And we would like to swap that around so that the shorter redirects the to the longer version.
That way no existing links will stop working, but gradually references to your repository, and more importantly Google's indexer will use the longer identifiable version.

Document URLs would need to be changed in a similar way, again any existing links would continue to work, but the promoted version of the links would change from
http://irep.ntu.ac.uk/12853/1/185527_3220%20Heasell%20prepublilsher.pdf
to
http://irep.ntu.ac.uk/id/eprint/12853/1/185527_3220%20Heasell%20prepublilsher.pdf

Justin

**Comment by jiadiyao** [comment]
We have made the changes described above locally and they have proved successful.
Now we have now also applied the changes to the EPrints core.
These changes are disabled by default, but can be enabled by updating your 20_base_urls.pl to include
	$c->{use_long_url_format} = 1; 

If you apply these changes and would like Google Scholar to prioritise a reindex of your repository, get in touch with us and we’ll pass the message along to them.


Justin

**Comment by jesusbagpuss** [comment]
Hi Jiadi,
I can see the logic in this, but I think there are other aspects that need a bit more consideration.
For an item that is not in the live archive, the URL /id/eprint/XXX will take you to the login page, or the item control page.
For a retired item, the URL /XXX will take you to the tombstone page (which will link to other versions if they exist).
For other items, it will take you to a 404 page.

The login page returns a 401 - which is NOT correct in this instance.

I think this change needs a bit more thought about how non-live items are reflected to Google - and 'normal' users.

**Comment by jiadiyao** [comment]
Hi John, 
Thanks for you feedback! 
The changes we made did not alter the return code or any redirection already in place in EPrints. 
The odd return code for the login page was there before. What happens is that the login cgi script is a secured page, which would prompt user to login first. Once the user is logged in, it just redirect to whatever the "target" parameter says.

**Comment by prazetyo** [comment]
Do I put this code directly in archive/cfg/cfg.d/20_baseurls.pl in any line? because I see this code is not available in the file.

thank you.

**Comment by prazetyo** [comment]
Hi Jiadi,
if I upgrade from 3.3.12 to 3.4 and use use_long_url_format, is there no problem with the url that Google Scholar indexed earlier in version 3.3.12?

Agung Prasetyo W.

**Comment by DavidGrau** [comment]
> We have made the changes described above locally and they have proved successful.
> Now we have now also applied the changes to the EPrints core.
> These changes are disabled by default, but can be enabled by updating your 20_base_urls.pl to include
> $c->{use_long_url_format} = 1;
> 
> If you apply these changes and would like Google Scholar to prioritise a reindex of your repository, get in touch with us and we’ll pass the message along to them.
> 
> Justin

Hi Jiadi, 
I already have the changes applied with $c->{use_long_url_format} = 1; I only have to edit my sitemap generator so that it also shows the long url.

My question below is; How can we speed up the indexing in Google Scholar? 

EDIT: Finally i found a solution to solve Scholar index problems. 
Eprints have 3 functions to redirect items in ..\perl_lib\EPrints\Apache\Rewrite.pm 
![image](https://user-images.githubusercontent.com/5485131/165731805-474f06be-c654-49bd-8746-05868b8dff27.png)

When use_long_url_format is set to 1 Rewrite.pm runs this code:
![image](https://user-images.githubusercontent.com/5485131/165732233-91c9cce8-2342-416a-aea7-76872679ba18.png)


Just change redir_see_other for redir_permanent , Google not index pages that follows 302 or 303 redirects, but yes with 301. Now google shows our repository items in scholar search engine.

**Comment by glen-lee** [comment]
> We have made the changes described above locally and they have proved successful. Now we have now also applied the changes to the EPrints core. These changes are disabled by default, but can be enabled by updating your 20_base_urls.pl to include $c->{use_long_url_format} = 1;
> 
> If you apply these changes and would like Google Scholar to prioritise a reindex of your repository, get in touch with us and we’ll pass the message along to them.
> 
> Justin

Hi Justin,
Sorry for commenting on a closed Issue. I have applied these changes and our repository is now accessible via a long url format. Is the priority indexing still possible? We have 20k+ items and it'd be great if we can get them to Google Scholar quicker :)

**Comment by jb4** [comment]
Hello.  I don’t believe it to be necessary to contact Google Scholar on this point, once their indexer notices your repository, it should be reindexed pretty quickly.  Regards -- Justin



From: Glen ***@***.***>
Date: Monday, 18 September 2023 at 10:54
To: eprints/eprints ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [eprints/eprints] Contents on EPrints repository is not featuring on Google Scholar (#450)
CAUTION: This e-mail originated outside the University of Southampton.

We have made the changes described above locally and they have proved successful. Now we have now also applied the changes to the EPrints core. These changes are disabled by default, but can be enabled by updating your 20_base_urls.pl to include $c->{use_long_url_format} = 1;

If you apply these changes and would like Google Scholar to prioritise a reindex of your repository, get in touch with us and we’ll pass the message along to them.

Justin
Hi Justin

Sorry for commenting on a closed Issue. I have applied these changes and our repository is now accessible via a long url format. Is the priority indexing still possible? We have 20k+ items and it'd be great if we can get them to Scholar quicker :)

**Comment by drn05r** [comment]
In reply to mention in #529: Google Scholar tend to use the year browse view as an entry point and I have just checked yours and this all looks correct.  I can see you have HTTPS across your site and I see no security warnings when loading abstract pages.  I can also see both the links from the year browse view and the primary URLs used for abstract pages are the long URLs (i.e. /id/eprints/1234 rather than just /1234). 

You have said you have left this three months to allow time for indexing, so you have exhausted everything that we are aware you can do to initiate indexing by Google Scholar.  Checking regular Google, I can see you have over 100,000 pages indexed, so Google knows you exist and can successfully index abstract pages.  I am not currently aware of any EPrints research publication repositories that meet all of these criteria and return no Google Scholar results.

Unfortunately, I think the only option left is to try contacting Google Scholar again and seeing if they can give you an explanation.  I appreciate they are not particularly speedy at replying to such emails but I am out of other potential solutions.
