### ISSUE TITLE
SEO friendly path

### ISSUE THREAD

**Issue by denics** [eprints/eprints#451]
This is related to #450 lately solved by @jiadiyao . I have been thinking about this since a while and perhaps it can be a good idea, but I need your core feedback :) 
It would be interesting to have "SEO friendly" path alias? As for today each record has a numeric URI, which is good, with the new developments done in #450 now they'll go under /id/eprint/xxx (that maybe should become "customisable", so that instead I can keep nothing, or having /book/xxx or /thesis/xxx or even /[type]/xxx) . 
My request is if it would be a good idea to have a path alias like /id/eprint/long-life-eprints pointing to /id/eprint/xxx for the publication "the long life of eprints". Surely, from a SEO point of view this make sense.

**Comment by jiadiyao** [comment]
The very reason we made this change was to give Google Scholar a particular URL syntax to match, so that they can tell it is a EPrints repository without making any request at all. Making it configurable defeats this. Once they start requesting the URL, they can get back the item type, publication titles anyway, no need to put them in the path. 

In addition, putting these information in the URL means the URL is no longer stable (e.g. it changes from /book/xxx to /article/xxx when you change item type)
