### ISSUE TITLE
BibTeX export: wrong quote encoding

### ISSUE THREAD

**Issue by dennmuel** [eprints/eprints#510]
Hi all,

we have an eprint with this title:
`‘I feel better when…’: An analysis of the memory-experience gap for peoples’ estimates of the relationship between health behaviours and experiences`

When exported to BibTeX however, it looks like this:
`title = {?I feel better when??: An analysis of the memory-experience gap for peoples? estimates of the relationship between health behaviours and experiences},`

Notice the questionmarks around the beginning of the title and the one replacing the "...". I guess they originate from [this line](https://github.com/eprints/eprints/blob/cf9769d3f826d5c579dd61c2c0ed1320018ebb56/perl_lib/TeX/Encode/BibTeX.pm#L40). How can we fix the encoding for these characters?

**Comment by drn05r** [comment]
If this is essential for you personally, I would advise creating your own version of the BibTeX exporter and manage would do with the characters that currently get mapped to '?'.  Anything code above the line you pointed out could change quotes or ellipsis into a LaTeX encoding (e.g. left quote is \lq and right quote is \rq and ellipsis is \ldots).  The problem is knowing what you need to match against to do this transformations.

More generally, I can see that other system (e.g. Zotero) have improved BibTeX exporters that have a good go at doing these transformations.  Maybe it is something that can be looked into.  Maybe, allow the export plugin to load a set of specific transformations, then if they had not all been captured, the repository admin could just add the extra ones they need.

**Comment by drn05r** [comment]
Actually this should already be done by charmap.pm unless the characters are actually something else and just look like left quote, right quote and ellipsis.  I will see if I can reproduce.

**Comment by drn05r** [comment]
So it looks as though even the CPAN's TeX/Encode/charmap.pm only includes LaTeX to hex character mappings and not the other way round, so that is why these three characters appear as question marks.  There is nothing to stop you editing EPrints TeX/Encode/charmap.pm to include the following three lines inside %CHARS:

```
chr(0x2018) => "\\textquoteleft", # ‘
chr(0x2019) => "\\textquoteright", # ’
chr(0x2026) => "\\textellipsis", # …
```

This would allow the transformations you want rather than getting '?'s.  However, it seems odd these would not already be in place charmap.pm, so I would advise careful use.  I have read around and some tools have problems dealing with some of these characters, so maybe this is why they are not currenly transformed.

**Comment by dennmuel** [comment]
Thank you very much for investigating, @drn05r! That was very helpful. :)
